import rightside from "./modules/rightside-menu.js";
rightside();
import mobileNav from "./modules/mobile-nav.js";
mobileNav();
import topSlider from "./modules/top-slider.js";
topSlider();
import worksPath from "./modules/works-path.js";
worksPath();
import gallery from "./modules/gallery.js";
gallery();
import popupSlider from "./modules/popup-slider.js";
popupSlider();
import popup from "./modules/popup.js";
popup();
import validation from "./modules/validation.js";
validation();
import footerFormValid from "./modules/footer-form.js";
footerFormValid();
import popupVideo from "./modules/popup-video.js";
popupVideo();
import animation from "./modules/animation.js";
animation();
import counter from "./modules/counter.js";
counter();
import articleSlider from "./modules/article-slider.js";
articleSlider();
import blogPageSlider from "./modules/blog-page-slider.js";
blogPageSlider();
import asideBarSinglePost from "./modules/aside-bar-singlePost.js";
asideBarSinglePost();
import comments from "./modules/comments.js";
comments();
import search from "./modules/search.js";
search();
import validateFormContact from "./modules/contact.js";
validateFormContact();
import contactSlider from "./modules/contact-slider.js";
contactSlider();
